#!/bin/bash

[[ $(uname) -eq "Darwin" ]] && NL=$'\\\n' || NL="\n"

# Skip on amending messages
IS_AMEND=$(ps -ocommand= -p $PPID | grep -e '--amend');

if [ -z "$IS_AMEND" ]; then
  # Include any branches for which you wish to disable this script
  if [ -z "$BRANCHES_TO_SKIP" ]; then
    BRANCHES_TO_SKIP=(main master develop release)
  fi

  # Get the current branch name and check if it is excluded
  BRANCH_NAME=$(git symbolic-ref --short HEAD)
  BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

  # Trim it down to get the parts we're interested in
  TRIMMED=$(echo $BRANCH_NAME | sed -e 's:^\([^-]*-[^-]*\)-.*:\1:')

  # If it isn't excluded, preprend the trimmed branch identifier to the given message 
  if [ -n "$BRANCH_NAME" ] &&  ! [[ $BRANCH_EXCLUDED -eq 1 ]]; then

    TICKET=$(basename $TRIMMED | tr '[:lower:]' '[:upper:]')
    CHANGE=$(dirname $TRIMMED | tr '[:upper:]' '[:lower:]')
    LINK="https:\/\/kanasoftware.jira.com\/browse\/$TICKET"

    sed -i.bak -e "1s/^/$TICKET $CHANGE: /" \
    -e "\$s/\$/$NL$NL$LINK/" \
    $1
  fi
fi
